=== Ashwin-2147213/userrxml/user.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="offer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="no" type="xs:integer"></xs:element>
                            <xs:element name="plan" type="xs:integer"></xs:element>
                            <xs:element name="validity" type="xs:integer"></xs:element>
                            <xs:element name="subscription" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>

   
    
    <xs:element name="no">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="00"/>
                <xs:maxInclusive value="04"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="plan">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="300"/>
                <xs:maxInclusive value="1000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="validity">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="01"/>
                <xs:maxInclusive value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== Ashwin-2147213/userrxml/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="user.xsl"?>
<User xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="user.xsd">
<offers>
    <offer no='01'>
        <plan>999</plan>
        <validity>24</validity>
        <subscription>l</subscription>
        <description>can attend different webinars and can consult to lawyers personally</description>
    
    </offer>

    <offer no='02'>

        <plan>599</plan>
        <validity>24</validity>
        <subscription>l</subscription>
        <description>can attend different webinars</description>
    
        </offer>

    <offer no='03'>

        <plan>399</plan>
        <validity>24</validity>
        <subscription>E</subscription>
        <description>can have an access to different journals of different lawyers</description>
    
    </offer>

</offers>

</User>
